Include `shuffles` in `PinnedConstraintSystem::fmt`
privacy-scaling-explorations/halo2 pull request #195
Opened 2023-08-23 18:13 UTC by therealyingtong

2023-08-24 02:54 UTC, han0110 approved these changes
LGTM! Nice catch.

(the clippy error should be fixed after #192 is merged)

2023-09-06 07:52 UTC, han0110 commented
Just realized the change might lead to different `transcript_repr` even the circuit doesn't use `shuffle`, so I think to keep backward compatability we need to skip the `shuffle` field when it's empty.

2023-09-06 07:54 UTC, han0110 requested changes

2023-09-06 07:54 UTC, han0110 commented on halo2_proofs/src/plonk/circuit.rs
> +            .field("shuffles", self.shuffles)
```suggestion
            .field("lookups", self.lookups);
        if !self.shuffles.is_empty() {
            debug_struct.field("shuffles", self.shuffles);
        }
        debug_struct
```

2023-11-10 07:15 UTC, CPerezz approved these changes
LGTM!

2023-11-10 07:33 UTC, closed without merging

2023-11-10 07:33 UTC, CPerezz commented
Closing as @han0110 already cherry-picked this in  #226